printWidth: 100
tabWidth: 2
useTabs: false
semi: true
singleQuote: true
quoteProps: preserve
trailingComma: all
bracketSpacing: true
arrowParens: avoid
proseWrap: preserve
htmlWhitespaceSensitivity: strict
endOfLine: lf
